name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Build and run tests in Docker
      run: |
        docker build -t alfredgtd-test .
        docker run alfredgtd-test
    
    - name: Verify test output
      run: |
        echo "Tests completed successfully!"